#	BSDI $Id: Makefile,v 1.2 1993/03/23 02:25:20 polk Exp $
#	from @(#)Makefile	5.1 (Berkeley) 5/3/91

PROG=	dd
SRCS=	args.c conv.c conv_tab.c dd.c misc.c position.c
NOMAN=	noman
#LDFLAGS=-N
.PATH:	/usr/src/bin/dd

.include <bsd.prog.mk>
