#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:27:20 polk Exp $

.include "../Makefile.defs"

LIB=	driver
SRCS=	input.cc printer.cc
NOPROFILE=noprofile
NOMAN=	noman

install:

.include "../Makefile.common"
.include <bsd.lib.mk>

.SUFFIXES: .cc
