LIB=c
NOPROFILE=
SRCS+=	concat.c lfind.c listsort.c newprintf.c newstr.c newnstr.c \
	otol.c rfc822time.c sobuf.c strclr.c strcpyend.c \
	strncpyend.c strstr.c uucplock.c xtol.c

# strccmp.c strnccmp.c unsetenv.c bsearch.c 

# This library is not installed, *especially* here
install:

.include <bsd.lib.mk>
.include <bsd.man.mk>
