#	BSDI $Id: Makefile,v 1.27 1994/01/29 17:15:52 polk Exp $

SUBDIR=	bash basic calc cdif checksendmail cshar daemon dig dvijep dvips \
	elm elvis emacs flexfax ghostview gmake gpatch gs gzip irc jove ksh \
	less lprps md5 mh midi mtools nenscript pcnfsd perl pico psgraph \
	sblaster sc screen sdif shs tcl tcsh te tex texi2roff \
	texinfo tk top wdiff zip zmodem zsh
# SUBDIR+=isode

beforeinstall:
	-@mkdir ${DESTDIR}/usr/contrib

.include <bsd.subdir.mk>
