#! /bin/sh
#	$Header: /bsdi/MASTER/BSDI_OS/contrib/flexfax/etc/faxd,v 1.1.1.1 1994/01/14 23:09:40 torek Exp $
#
# FlexFAX Facsimile Software
#
# Copyright (c) 1990, 1991, 1992, 1993 Sam Leffler
# Copyright (c) 1991, 1992, 1993 Silicon Graphics, Inc.
# 
# Permission to use, copy, modify, distribute, and sell this software and 
# its documentation for any purpose is hereby granted without fee, provided
# that (i) the above copyright notices and this permission notice appear in
# all copies of the software and related documentation, and (ii) the names of
# Sam Leffler and Silicon Graphics may not be used in any advertising or
# publicity relating to the software without the specific, prior written
# permission of Sam Leffler and Silicon Graphics.
# 
# THE SOFTWARE IS PROVIDED "AS-IS" AND WITHOUT WARRANTY OF ANY KIND, 
# EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY 
# WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  
# 
# IN NO EVENT SHALL SAM LEFFLER OR SILICON GRAPHICS BE LIABLE FOR
# ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND,
# OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF 
# LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE 
# OF THIS SOFTWARE.
#
#	fax server control

IS_ON=/etc/chkconfig
DIR=/usr/spool/fax
FAXD=/usr/etc/faxd

if test ! -x $IS_ON ; then
    IS_ON=true
fi

if $IS_ON verbose ; then
    ECHO=echo
else		# For a quiet startup and shutdown
    ECHO=:
fi

case $1 in
'start')
	if $IS_ON fax && test -x $FAXD; then
	    $ECHO "Fax servers:\c"
	    cd $DIR
	    for fifo in FIFO.*
	    do
		modem=`expr ${fifo} : '.*\.\(.*\)'`
		if test -r etc/config.${modem}; then
		    $ECHO " $modem\c"
		    $FAXD -m /dev/`echo $modem | tr _ /` &
		fi
	    done
	    $ECHO "."
	fi
	;;
'stop')
	cd $DIR
	for fifo in FIFO.*
	do
	    bin/faxquit $fifo
	done
	;;
*)
	echo "usage: /etc/init.d/faxd {start|stop}"
	;;
esac
