#	BSDI $Id: Makefile,v 1.7 1994/01/26 19:32:23 donn Exp $
#	@(#)Makefile	5.15.1.2 (Berkeley) 5/8/91

Missing: adventure boggle ching dungeon phantasia warp 

SUBDIR=	arithmetic atc backgammon battlestar bcd caesar canfield \
	cribbage dm factor fish fortune gnuchess hack hangman hunt larn \
	mille monop morse number pom ppt primes quiz rain robots rogue \
	sail snake trek wargames worm worms wump

.include <bsd.subdir.mk>
