#	BSDI Makefile,v 1.3 1992/01/04 19:13:06 kolstad Exp
#	from @(#)Makefile	5.3 (Berkeley) 5/11/90

PROG=	diskdefect
SRCS=	diskdefect.c drck_scan.c errlib.c
NOMAN=	noman
LDFLAGS+=-N

.PATH:	/usr/src/sbin/diskdefect

.include <bsd.prog.mk>
