#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:27:13 polk Exp $

SUBDIR= libbib libdriver libgroff addftinfo afmtodit eqn devX100 \
	devX100-12 devX75 devX75-12 devascii devdvi devlatin1 devps \
	grodvi groff grog grops grotty indxbib lkbib lookbib man mm \
	nroff pfbtops pic psbb refer soelim tbl tfmtodit tmac troff

.include <bsd.subdir.mk>
