#	BSDI $Id: Makefile,v 1.2 1993/11/28 00:13:56 donn Exp $
#	@(#)Makefile	5.5 (Berkeley) 6/29/90

PROG=	inetd
LDADD=	-lutil
MAN8=	inetd.0
MLINKS=	inetd.8 inetd.5
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
