NOPROFILE= 
LIB=	acu

SRCS+=	att2224.c bsdtcp.c cds224.c df12.c df2.c dk.c dn.c \
	hys.c hys24.c hysq.c hysv.c \
	mic.c nov.c pen.c pnet.c rvmacs.c sy.c unet.c \
	va212.c va811.c va820.c vad.c vent.c vmacs.c

# This library is not installed
install:

.include <bsd.lib.mk>
.include <bsd.man.mk>
