#!/usr/bin/perl

# $Header: /bsdi/MASTER/BSDI_OS/contrib/perl/grot/eg/g/ged,v 1.1.1.1 1992/07/27 23:24:08 polk Exp $

# Does inplace edits on a set of files on a set of machines.
#
# Typical invokation:
#
#	ged vax+sun /etc/passwd
#	s/Freddy/Freddie/;
#	^D
#

$class = shift;
$files = join(' ',@ARGV);

die "Usage: ged class files <perlcmds\n" unless $files;

exec "gsh", $class, "-d", "perl -pi.bak - $files";

die "Couldn't execute gsh for some reason, stopped";
