#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:28:27 polk Exp $

.include "../Makefile.defs"

PROG=	grog
SRCS=
STRIP=

depend:

grog: grog.pl
	cp ${.CURDIR}/grog.pl grog
	
.include "../Makefile.common"
.include <bsd.prog.mk>
