#	BSDI	$Id: Makefile,v 1.2 1994/01/06 02:15:26 polk Exp $
#	@(#)Makefile	5.1 (Berkeley) 6/25/90

LIB=	acl
CFLAGS+=-DDEBUG -DKERBEROS -I${.CURDIR}/../include
SRCS=	acl_files.c
NOPROFILE=noprofile

.include <bsd.lib.mk>
