#       BSDI $Id: Makefile,v 1.1.1.1 1992/09/28 20:08:31 trent Exp $

LIB=            args
SRCS=           Args.c ArgsUsage.c DoArgs.c
NOPROFILE=      noprofile

# The library is not installed
install:

.include <bsd.lib.mk>
.include <bsd.man.mk>
