#	BSDI	$Id: Makefile,v 1.2 1994/01/30 19:52:55 polk Exp $

MAN1=	after.0 bind.0 button.0 canvas.0 checkbutton.0 destroy.0 \
	dialog.0 entry.0 exit.0 focus.0 frame.0 grab.0 label.0 \
	lbSingSel.0 listbox.0 lower.0 menu.0 menubar.0 menubutton.0 \
	message.0 option.0 options.0 pack-old.0 pack.0 place.0 \
	radiobutton.0 raise.0 scale.0 scrollbar.0 selection.0 send.0 \
	text.0 tk.0 tkerror.0 tkvars.0 tkwait.0 toplevel.0 update.0 \
	winfo.0 wm.0

MANDIR?=/usr/contrib/tclman/cat
MANSRCDIR?=/usr/contrib/tclman/man

.include <bsd.prog.mk>
