#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:27:28 polk Exp $

.include "../Makefile.defs"

PROG=	tbl
SRCS=   main.cc table.cc
LDADD+=	${LIBGROFF} ${LIBGCC}
DPADD+=	${LIBGROFF} ${LIBGCC}

.include "../Makefile.common"
.include <bsd.prog.mk>
