#	@(#)Makefile	5.6 (Berkeley) 2/19/92

PROG=	mtree
MAN8=	mtree.0
#CFLAGS+=-DDEBUG
SRCS=	compare.c crc.c create.c misc.c mtree.c spec.c verify.c
.PATH:	${.CURDIR}/../../usr.bin/cksum

.include <bsd.prog.mk>
