#!/bin/sh -
#
#	BSDI	$Id: weekly,v 1.6 1994/01/31 16:46:28 polk Exp $
#	from @(#)weekly	5.14 (Berkeley) 6/23/91
#

PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/libexec
export PATH

host=`hostname -s`
echo "Subject: $host weekly run output"

#
# rotate /path/file 9 8 7 6 5 4 3 2 1 0
#
rotate() {
	file="$1"; shift
	rm -f "$file.$1"
	for i in "$@"; do
		[ "$i" = "0" ] && j="" || j=".`expr $i - 1`"
		[ -f "$file$j" ] && mv -f "$file$j" "$file.$i"
	done
	cp /dev/null "$file"; chmod 644 "$file"
}

if [ -f /etc/uucp/weekly ]; then
	echo ""; echo "Cleaning up UUCP:"
	su -m uucp -fc /etc/uucp/weekly
fi

echo ""; echo "Rotating messages:"
rotate /var/log/messages 3 2 1 0
kill -1 `cat /var/run/syslog.pid`

echo ""; echo "Rotating cron log:"
rotate /var/log/cron 3 2 1 0
kill -1 `cat /var/run/syslog.pid`

[ -f /etc/weekly.local ] && sh /etc/weekly.local

exit 0
