***************
*** 8,17 ****
  	pmap_clnt.c pmap_getmaps.c pmap_getport.c pmap_prot.c \
  	pmap_prot2.c pmap_rmt.c rpc_prot.c rpc_commondata.c rpc_callmsg.c \
  	svc.c svc_auth.c svc_auth_unix.c svc_raw.c svc_run.c svc_simple.c \
! 	svc_tcp.c svc_udp.c xdr.c xdr_array.c xdr_mem.c \
  	xdr_rec.c xdr_reference.c xdr_stdio.c
- 
- UNSUPPORTED=	xdr_float.c 
  
  HDRS=	auth.h auth_unix.h clnt.h pmap_clnt.h \
  	pmap_prot.h pmap_rmt.h rpc.h rpc_msg.h svc.h svc_auth.h types.h xdr.h
--- 8,15 ----
  	pmap_clnt.c pmap_getmaps.c pmap_getport.c pmap_prot.c \
  	pmap_prot2.c pmap_rmt.c rpc_prot.c rpc_commondata.c rpc_callmsg.c \
  	svc.c svc_auth.c svc_auth_unix.c svc_raw.c svc_run.c svc_simple.c \
! 	svc_tcp.c svc_udp.c xdr.c xdr_array.c xdr_float.c xdr_mem.c \
  	xdr_rec.c xdr_reference.c xdr_stdio.c
  
  HDRS=	auth.h auth_unix.h clnt.h pmap_clnt.h \
  	pmap_prot.h pmap_rmt.h rpc.h rpc_msg.h svc.h svc_auth.h types.h xdr.h
