LIB=
NOPROFILE=
NOMAN=
SRCS+=	FastMalloc.c \
	CheckDirs.c Checkeuid.c CheckUserPath.c ChNodeDir.c \
	CopyFdToFd.c Create.c CreateWf.c Debug.c \
	DecodeNum.c EchoArgs.c EncodeNum.c Error.c Execute.c \
	ExpandArgs.c ExpandString.c ExpFn.c Fatal.c \
	FindFile.c FindSysEntry.c FreeStr.c FSFree.c \
	GetErrFile.c GetLine.c GetNetUid.c GetUser.c HashName.c InitParams.c \
	ISO_time.c LoadSys.c Log.c Mail.c MakeErrFile.c Malloc.c Malloc0.c MesgN.c \
	MesgV.c MkDirs.c MoveCp.c NextArg.c NodeName.c QueueCmd.c ReadFile.c \
	NameProg.c ScanSys.c SetNetUid.c SetTimes.c \
	SplitArgs.c SplitSpace.c SplitSysName.c StripEnv.c \
	SysFile.c SysWarn.c Trace.c \
	Uucico.c UUCP_time.c Uusched.c Uuxqt.c ValidChars.c \
	Version.c Warn.c WfName.c inet_ntoa.c strings.c

# This library is not installed
install:

.include <bsd.lib.mk>
.include <bsd.man.mk>
