0 0
get
/tmp/gnutest/1.bt
level
1 15
white
post
go
get
/tmp/gnutest/2.bt
level
1 15
white
post
go
get
/tmp/gnutest/3.bt
level
1 15
white
post
go
get
/tmp/gnutest/4.bt
level
1 15
white
post
go
get
/tmp/gnutest/5.bt
level
1 15
white
post
go
get
/tmp/gnutest/6.bt
level
1 15
black
post
go
get
/tmp/gnutest/7.bt
level
1 15
black
post
go
get
/tmp/gnutest/8.bt
level
1 15
white
post
go
get
/tmp/gnutest/9.bt
level
1 15
black
post
go
get
/tmp/gnutest/10.bt
level
1 15
white
post
go
get
/tmp/gnutest/11.bt
level
1 15
black
post
go
get
/tmp/gnutest/12.bt
level
1 15
white
post
go
get
/tmp/gnutest/13.bt
level
1 15
white
post
go
get
/tmp/gnutest/14.bt
level
1 15
white
post
go
get
/tmp/gnutest/15.bt
level
1 15
white
post
go
get
/tmp/gnutest/16.bt
level
1 15
black
post
go
get
/tmp/gnutest/17.bt
level
1 15
white
post
go
get
/tmp/gnutest/18.bt
level
1 15
white
post
go
get
/tmp/gnutest/19.bt
level
1 15
black
post
go
get
/tmp/gnutest/20.bt
level
1 15
white
post
go
get
/tmp/gnutest/21.bt
level
1 15
white
post
go
get
/tmp/gnutest/22.bt
level
1 15
white
post
go
get
/tmp/gnutest/23.bt
level
1 15
white
post
go
get
/tmp/gnutest/24.bt
level
1 15
white
post
go
get
/tmp/gnutest/25.bt
level
1 15
black
post
go
get
/tmp/gnutest/26.bt
level
1 15
white
post
go
get
/tmp/gnutest/27.bt
level
1 15
white
post
go
get
/tmp/gnutest/28.bt
level
1 15
white
post
go
get
/tmp/gnutest/29.bt
level
1 15
white
post
go
get
/tmp/gnutest/30.bt
level
1 15
white
post
go
quit
