PROG=dig
SRCS=	dig.c herror.c res_comp.c res_debug.c res_init.c res_mkquery.c \
	res_query.c res_send.c strcasecmp.c gethostnamadr.c sethostent.c \
	qtime.c list.c
CFLAGS+=-DDEBUG

.include <bsd.prog.mk>
