#	BSDI $Id: Makefile,v 1.4 1994/02/01 15:04:20 polk Exp $

PROG=	uusched
MAN8=	uusched.0
LDADD+=	-lutil
DPADD+=	${LIBUTIL}

BINDIR=	/usr/libexec
BINMODE=6110

.include <bsd.prog.mk>
.include <bsd.man.mk>
