#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/21 04:23:08 polk Exp $

LIB=	rcs
SRCS=   maketime.c partime.c rcsedit.c rcsfcmp.c rcsfnms.c rcsgen.c \
	rcskeep.c rcskeys.c rcslex.c rcsmap.c rcsrev.c rcssyn.c \
	rcsutil.c
NOMAN=	noman
NOPROFILE=noprofile

install:

.include <bsd.lib.mk>
