#	BSDI $Id: Makefile,v 1.12 1994/01/06 00:16:41 polk Exp $
#	from @(#)Makefile	5.25.1.1 (Berkeley) 5/7/91

# Missing: libdbm libmp libplot

SUBDIR=	csu.${MACHINE} libc libcdrom libcompat libcurses libedit \
	libg++ libkvm libm libnm libnewcurses libresolv librpc/rpc \
	libterm libutil liby

.include <bsd.subdir.mk>
