#	BSDI	$Id: Makefile,v 1.2 1994/01/30 19:51:48 polk Exp $

MAN1=	Tcl.0 append.0 array.0 break.0 case.0 catch.0 cd.0 close.0 \
	concat.0 continue.0 eof.0 error.0 eval.0 exec.0 exit.0 expr.0 \
	file.0 flush.0 for.0 foreach.0 format.0 gets.0 glob.0 global.0 \
	history.0 if.0 incr.0 info.0 join.0 lappend.0 library.0 \
	lindex.0 linsert.0 list.0 llength.0 lrange.0 lreplace.0 \
	lsearch.0 lsort.0 open.0 pid.0 proc.0 puts.0 pwd.0 read.0 \
	regexp.0 regsub.0 rename.0 return.0 scan.0 seek.0 set.0 source.0 \
	split.0 string.0 switch.0 tclvars.0 tell.0 time.0 trace.0 \
	unknown.0 unset.0 uplevel.0 upvar.0 while.0

MANDIR?=/usr/contrib/tclman/cat
MANSRCDIR?=/usr/contrib/tclman/man

.include <bsd.prog.mk>
