#!/usr/bin/perl -P

# $Header: /bsdi/MASTER/BSDI_OS/contrib/perl/grot/eg/changes,v 1.1.1.1 1992/07/27 23:24:06 polk Exp $

($dir, $days) = @ARGV;
$dir = '/' if $dir eq '';
$days = '14' if $days eq '';

# Masscomps do things differently from Suns

#if defined(mc300) || defined(mc500) || defined(mc700)
open(Find, "find $dir -mtime -$days -print |") ||
	die "changes: can't run find";
#else
open(Find, "find $dir \\( -fstype nfs -prune \\) -o -mtime -$days -ls |") ||
	die "changes: can't run find";
#endif

while (<Find>) {

#if defined(mc300) || defined(mc500) || defined(mc700)
    $x = `/bin/ls -ild $_`;
    $_ = $x;
    ($inode,$perm,$links,$owner,$group,$size,$month,$day,$time,$name)
      = split(' ');
#else
    ($inode,$blocks,$perm,$links,$owner,$group,$size,$month,$day,$time,$name)
      = split(' ');
#endif

    printf("%10s%3s %-8s %-8s%9s %3s %2s %s\n",
	    $perm,$links,$owner,$group,$size,$month,$day,$name);
}

