#!/usr/bin/perl -P

# $Header: /bsdi/MASTER/BSDI_OS/contrib/perl/grot/eg/scan/scan_ps,v 1.1.1.1 1992/07/27 23:24:08 polk Exp $

# This looks for looping processes.

#if defined(mc300) || defined(mc500) || defined(mc700)
open(Ps, '/bin/ps -el|') || die "scan_ps: can't run ps";

while (<Ps>) {
    next if /rwhod/;
    print if index(' T', substr($_,62,1)) < 0;
}
#else
open(Ps, '/bin/ps auxww|') || die "scan_ps: can't run ps";

while (<Ps>) {
    next if /dataserver/;
    next if /nfsd/;
    next if /update/;
    next if /ypserv/;
    next if /rwhod/;
    next if /routed/;
    next if /pagedaemon/;
#ifdef vax
    ($user,$pid,$cpu,$mem,$sz,$rss,$tt,$stat,$start,$time) = split;
#else
    ($user,$pid,$cpu,$mem,$sz,$rss,$tt,$stat,$time) = split;
#endif
    print if length($time) > 4;
}
#endif
