#	BSDI $Id: Makefile,v 1.5 1994/02/01 14:50:48 polk Exp $

NOMAN=	noman
all:
clean:
cleandir:
depend:
obj:
objdir:
mansrcinstall:

install:
	install -c -o bin -g bin -m 555  psif-text ${DESTDIR}/usr/contrib/lib/lprps/
	install -c -o bin -g bin -m 555  psif-ps ${DESTDIR}/usr/contrib/lib/lprps/
	install -c -o bin -g bin -m 444  banner.ps ${DESTDIR}/usr/contrib/lib/lprps/
