#!/bin/csh -f
# @(#) $Header: /bsdi/MASTER/BSDI_OS/usr.sbin/tcpdump/grot/ostype,v 1.1.1.1 1993/03/08 17:46:15 polk Exp $ (LBL)
#
# Determine os type.
#
set os=`awk -f ostype.awk /etc/motd`
if ($os == "") exit 1
if ($os == "UNKNOWN") then
	if ( -f /hp-ux ) then
		set os="hpux"
	else if ( -f /etc/uerf ) then
		set os="ultrix"
	endif
endif
echo $os
if ($os == "UNKNOWN") exit 1
exit 0
