#!/bin/sh

if test $# -ne 2 ; then
	echo "Usage: cp oldfile newfile";
	exit 1;
fi

case $1 in
-*)
	echo "cp: this version doesn't take switches";
	exit 1;
	;;
esac

if test -d $1 ; then
	echo "cp: can't copy directories";
	exit 1;
fi

if test -d $2 ; then
	echo "cp: can only copy to files (specify the destination file name)";
	exit 1;
fi

if test ! -f $1 ; then
	echo "cp: source file doesn't exist";
	exit 1;
fi

cat $1 > $2
