/* s_filter.h created from s_filter.us by gencat on Sat Nov 14 21:02:00 EST 1992 */

#define FilterSet	0x10
#define FilterCantGetPasswdEntry	0x1
#define FilterUsage	0x2
#define FilterCouldntOpenLogFile	0x3
#define FilterCouldntGetRules	0x4
#define FilterCantOpenTempFileLeave	0x5
#define FilterMessageDeleted	0x6
#define FilterMailingMessage	0x7
#define FilterCantOpenTempFile2	0x8
#define FilterLoopDetected	0x9
#define FilterPopenFailed	0xa
#define FilterFromTheFilterOf	0xb
#define FilterXFilteredBy	0xc
#define FilterBeginMesg	0xd
#define FilterEndMesg	0xe
#define FilterCouldntCreateLockFile	0xf
#define FilterCantOpenMailBox	0x10
#define FilterSavedMessage	0x11
#define FilterCantSaveMessageToFolder	0x12
#define FilterCantOpenTempFile3	0x13
#define FilterExecutingCmd	0x14
#define FilterBadWaitStat	0x15
#define FilterForkFailed	0x16
#define FilterCantOpenEither	0x17
#define FilterCantOpenAny	0x18
#define FilterCantOpenAnyLeave	0x19
#define FilterUsingEmergMbox	0x1a
#define FilterCouldntReadRules	0x1b
#define FilterCouldntMallocFirst	0x1c
#define FilterErrorReadingRules1	0x1d
#define FilterCouldntMallocNew	0x1e
#define FilterErrorReadingRules2	0x1f
#define FilterErrorReadingRules3	0x20
#define FilterCantAllocRules	0x21
#define FilterContainsNotImplemented	0x22
#define FilterSender	0x23
#define FilterReturnAddress	0x24
#define FilterSubject	0x25
#define FilterReSubject	0x26
#define FilterDayOfMonth	0x27
#define FilterDayOfWeek	0x28
#define FilterMonth	0x29
#define FilterYear	0x2a
#define FilterHour	0x2b
#define FilterTime	0x2c
#define FilterErrorTranslatingMacro	0x2d
#define FilterAlways	0x2e
#define FilterRuleIf	0x2f
#define FilterNot	0x30
#define FilterAnd	0x31
#define FilterThen	0x32
#define FilterDelete	0x33
#define FilterSave	0x34
#define FilterCopyAndSave	0x35
#define FilterForward	0x36
#define FilterCopyAndForward	0x37
#define FilterLeave	0x38
#define FilterExecute	0x39
#define FilterAction	0x3a
#define FilterCantOpenFiltersum	0x3b
#define FilterWarningInvalidForShort	0x3c
#define FilterSumTitle	0x3d
#define FilterTotalMessagesFiltered	0x3e
#define FilterTotalMsgsFlrdPlural	0x3f
#define FilterErroneousRules	0x40
#define FilterErroneousRulesPlural	0x41
#define FilterDefaultRuleMesg	0x42
#define FilterAppliedTimes	0x43
#define FilterAppliedTimesPlural	0x44
#define FilterLeaveMesg	0x45
#define FilterDeleteMesg	0x46
#define FilterSaveMesg	0x47
#define FilterSaveCcMesg	0x48
#define FilterForwardMesg	0x49
#define FilterForwardCMesg	0x4a
#define FilterExecMesg	0x4b
#define FilterCantOpenFilterlog	0x4c
#define FilterExplicitLog	0x4d
#define FilterMailFrom	0x4e
#define FilterAbout	0x4f
#define FilterAddressedTo	0x50
#define FilterDeletedMesg	0x51
#define FilterSaveFailedMesg	0x52
#define FilterSavedMesg	0x53
#define FilterSavedAndPutMesg	0x54
#define FilterForwardedMesg	0x55
#define FilterForwardedAndPutMesg	0x56
#define FilterExecutedMesg	0x57
#define FilterPutMesg	0x58
#define FilterByRule	0x59
#define FilterTheDefaultAction	0x5a
#define FilterForkSaveFailed	0x5b
#define FilterRuleNum	0x5c
#define FilterOutOfMemory	0x5d
#define FilterExecuteAndSave	0x5e
#define FilterExecCMesg	0x5f
#define FilterExecutedSMesg	0x60
#define FilterCantCompileRegexp	0x61
#define FilterWholeRegsub	0x62
#define FilterRegsubOne	0x63
#define FilterRegsubTwo	0x64
#define FilterRegsubThree	0x65
#define FilterRegsubFour	0x66
#define FilterRegsubFive	0x67
#define FilterRegsubSix	0x68
#define FilterRegsubSeven	0x69
#define FilterRegsubEight	0x6a
#define FilterRegsubNine	0x6b
