#	BSDI $Id: Makefile,v 1.4 1994/01/29 16:30:04 polk Exp $

MAN1= mtools.0 
MAN5= mtoolsrc.0
NOPROG=noprog

SUBDIR=	lib mattrib mcd mcopy mdel mdir mformat mkmanifest mlabel mmd \
	mrd mread mren mtype mwrite


.include <bsd.prog.mk>
