#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:28:26 polk Exp $

.include "../Makefile.defs"

PROG=	afmtodit
SRCS=
STRIP=

afmtodit: afmtodit.pl
	cp ${.CURDIR}/afmtodit.pl afmtodit
	
depend:

.include "../Makefile.common"
.include <bsd.prog.mk>
