#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:27:52 polk Exp $

.include "../Makefile.defs"

PROG=	soelim
SRCS=   soelim.cc
LDADD+=	${LIBGROFF} ${LIBGCC}
DPADD+=	${LIBGROFF} ${LIBGCC}

.include "../Makefile.common"
.include <bsd.prog.mk>
