#
# @(#)Makefile	2.1 88/08/01 4.0 RPCSRC
#
# Makefile for rpc protocol compiler
# Copyright (C) 1987, Sun Microsystems, Inc.
#
PROG=	rpcgen
SRCS=	rpc_main.c \
	rpc_hout.c \
	rpc_cout.c \
	rpc_parse.c \
	rpc_scan.c \
	rpc_util.c \
	rpc_svcout.c \
	rpc_clntout.c
MAN1=	rpcgen.0

.include <bsd.prog.mk>
