.TH notes 1 "12 June 1992"
.IX notes
.SH NAME
.PP
notes \- generate random FM sounds

.SH SYNOPSIS
.PP
\f3notes\f1

.SH DESCRIPTION
.PP

\fInotes\fP loads random values into all of the various parameters for
each voice in the left and right channels of the Sound Blaster Pro FM
chips. It's mostly just a program to test the FM synthesizer, but
music is a subjective thing. :-)

It cycles through all nine voices of the each channel, alternating
between Operator 0 and Operator 1.  This is intended to show two
things: Your FM device is working, and the general capabilities of the
FM chips.

.SH BUGS
.PP
Tends to hammer the machine.
.SH AUTHOR
Steve Haehnichen <shaehnic@ucsd.edu>
