#!/bin/sh -
PROG=${1-UNKNOWN}
VERSION=${2-../VERSION}

if [ ! -f .version ]; then
  echo 0 > .version
fi

RUN="`cat .version`"
RUN="`expr $RUN + 1`"
echo $RUN > .version

DATE="`date`"

if [ -f "$VERSION" ]; then
  FLAGS="`egrep '^[0-9a-zA-Z_]+=' "$VERSION" | tr '\012' ';'` "
else
  FLAGS=""
fi

echo "Version $PROG ${FLAGS}${DATE} (${RUN})";

rm -f version.c
cat > version.c << -EoF-
/*
 * version file for $PROG
 */
char * Version = "$PROG ${FLAGS}${DATE} (${RUN})";
-EoF-
