#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:28:28 polk Exp $

.include "../Makefile.defs"

PROG=	nroff
SRCS=
STRIP=

depend:

nroff: nroff.sh
	cp ${.CURDIR}/nroff.sh nroff
	
.include "../Makefile.common"
.include <bsd.prog.mk>
