#	BSDI $Id: Makefile,v 1.3 1992/01/04 19:13:06 kolstad Exp $
#	from @(#)Makefile	5.3 (Berkeley) 5/11/90

PROG=	bad144
MAN8=	bad144.0
.if ${MACHINE} == "vax"
MANSUBDIR=/vax
.elif ${MACHINE} == "i386"
MANSUBDIR=/i386
.endif

.include <bsd.prog.mk>
