#!/usr/bin/perl

#	BSDI	$Id: getioctlsizes,v 1.2 1994/01/06 06:56:10 polk Exp $

foreach $file ( ('/usr/include/sys/ioctl.h', '/usr/include/sys/ioctl_compat.h') ) {

	open (IOCTLS, $file) || die "$file open failed";

	while (<IOCTLS>) {
    		if (/^\s*#\s*define\s+\w+\s+_IO(R|W|WR)\('?\w+'?,\s*\w+,\s*([^)]+)/) {
			$need{$2}++;
    		} 
	}
}

foreach $key ( sort keys %need ) {
    print $key,"\n";
} 
