#	BSDI $Id: Makefile,v 1.2 1994/01/15 07:13:03 polk Exp $

.include "../../Makefile.inc"

PROG=	elvrec
CFLAGS+=	-I${.CURDIR}/../elvis -Dbsd
SRCS=	elvrec.c
BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
