#	BSDI $Id: Makefile,v 1.1.1.1 1993/12/22 06:27:21 polk Exp $

.include "../Makefile.defs"

LIB=	bib
SRCS=	common.cc index.cc linear.cc map.c search.cc
NOPROFILE=noprofile
NOMAN=	noman

install:

.include "../Makefile.common"
.include <bsd.lib.mk>

.SUFFIXES: .cc
