#	BSDI $Id: Makefile,v 1.2 1994/01/15 00:03:03 torek Exp $

# OUT: man
SUBDIR=	afm port/bsdi doc etc libtiff iv util \
	dialtest fax2ps faxalter faxanswer faxcover faxinfo faxd faxmail \
	faxquit faxrm faxstat     ondelay recvfax sendfax textfmt

.include <bsd.subdir.mk>
