#	BSDI	$Id: Makefile,v 1.1.1.1 1993/12/21 04:17:52 polk Exp $

# NOTE: order of subdirs is important -- support must be first and 
#	ftpd must be second

SUBDIR=support ftpd ftpcount ftpshut

.include <bsd.subdir.mk>
