.TH MPLAY 1 "3 August 1992"
.SH NAME
mplay \- play a standard MIDI file through a MPU-401 compatable device
.SH SYNOPSIS
.B mplay
[
.RB - rv
] [
.RB - t
tempo-scalar
] [
.RB - T
track-list
] [
[
.RB - R
]
midi-file ...
]
.SH DESCRIPTION
Used without arguments,
.B mplay
reads a standard
.SM MIDI
format [
.SM SMF
] file data from stdin,
converts it to a form suitable for
playing through a
.SM MPU-401
compatable device and sends the converted
data through the
device.
More than one 
.SM SMF
file can be sent through stdin
and new files will be processed until there
is no more data available.
.LP
Alternatively, mplay
can be run with the
.SM SMF
files specified on the command line.
.LP
In both cases, the files are loaded and processed individually
so there might be slight delays in the output between each file.
Also, if any file has more the 8 tracks, a warning is printed
to stdout and only the first 8 tracks are used.
.SH OPTIONS
.TP
.RB - r
This option causes the first
.SM SMF
file to repeat indefinitely.
This differs from the
.B R
option in that the file is only loaded once
and the repeat will incur no delay.
.TP
.RB - v
This options turns on verbose output.
When the
.SM SMF
file is processed, all
.SM META
events are printed to stdout.
Some other useful information is also printed.
.TP
.RB - t
This option takes a floating point argument.
It specifies a factor that will scale all
tempo values found in
the
.SM SMF
files.
The argument can range from 0 to 4,
other values will be silently chopped.
This option is implemented via the
.SM MSETRELTMP.
A maximum tempo value of 250 beats per minute and a minimum
value of 8 beats per minute are enforced.
.TP
.RB - T
This option takes an argument that specifies which tracks to play.
The argument is in the form of a list of integers separated by
','s or '-'s.
The '-' specifies an inclusive range between the two surrounding
integers, while the ',' separates individual integers.
.SM SMF
files of type 1 start with track 0, the tempo track and continue
to the number of tracks - 1.
.SM SMF
files of type 0 are logically split into a tempo track in position
0 and a data track in position 1.
.SM SMF
files of type 2 are treated like type 1 files.
If more than 8 tracks are specified, only the first 8 are used and
a warning is printed.
.TP
.RB - R
This is a different form of the repeat option.
It is only valid when
.SM SMF
files are specified on the command line.
It causes mplay to repeat playing the list
of
.SM MSF
files.
Since the files are loaded individually,
there might be a slight delay between playing the last
file and the first, and thus is not as desirable for repeating
only a signal file as the
.B r
option.
.SH FILES
.PD 0
.TP 20
.B /dev/midicntl
.TP
.B /dev/midicond
.TP
.B /dev/midi[0-7]
.PD
.SH "SEE ALSO"
.BR midi (4),
.BR smf (5)
